import { AiOutlineEye } from "react-icons/ai";

export const PostcardsData = [
    {
        posttitle: "As yen tumbles, gadget-loving Japan goes for secondhand iPhones",
        postsub: "As yen tumbles, gadget-loving Japan goes for secondhand iPhones As yen tumbles, gadget-loving Japan goes for secondhand iPhonesAs yen tumbles, gadget-loving Japan goes for secondhand iPhonesAs yen tumbles, gadget-loving Japan goes for secondhand iPhones",
        // posteyeicon : <AiOutlineEye/>,
        // postmsgicon : <TbMessage2/>,
        // postdateicon : <RxDot/>,
        postimageblog : '/images/blog-img1.jpg',
        postuser : '/images/user-2.jpg',
        postviewdata : '5235',
        posttotalmsg : '3',
        postdate : 'Wed, Jul 19',
        postreadtime : '2 min Read',
        posttype : 'Gadget',
    },
    {
        posttitle: "Why Figma is selling to Adobe for $20 billion",
        postsub: "Why Figma is selling to Adobe for $20 billionWhy Figma is selling to Adobe for $20 billionWhy Figma is selling to Adobe for $20 billionWhy Figma is selling to Adobe for $20 billion",
        // posteyeicon : <AiOutlineEye/>,
        // postmsgicon : <TbMessage2/>,
        // postdateicon : <RxDot/>,
        postimageblog : '/images/blog-img2.jpg',
        postuser : '/images/user-2.jpg',
        postviewdata : '8926',
        posttotalmsg : '3',
        postdate : 'Sun, Jul 16',
        postreadtime : '2 min Read',
        posttype : 'Design',
    },
    {
        posttitle: "Garmins Instinct Crossover is a rugged hybrid smartwatch",
        postsub: "Garmins Instinct Crossover is a rugged hybrid smartwatchGarmins Instinct Crossover is a rugged hybrid smartwatchGarmins Instinct Crossover is a rugged hybrid smartwatch",
        // posteyeicon : <AiOutlineEye/>,
        // postmsgicon : <TbMessage2/>,
        // postdateicon : <RxDot/>,
        postimageblog : '/images/blog-img3.jpg',
        postuser : '/images/user-2.jpg',
        postviewdata : '8108',
        posttotalmsg : '3',
        postdate : 'Sat, Jul 15',
        postreadtime : '2 min Read',
        posttype : 'Gadget',
    },
    {
        posttitle: "As yen tumbles, gadget-loving Japan goes for secondhand iPhones",
        postsub: "As yen tumbles, gadget-loving Japan goes for secondhand iPhones As yen tumbles, gadget-loving Japan goes for secondhand iPhonesAs yen tumbles, gadget-loving Japan goes for secondhand iPhonesAs yen tumbles, gadget-loving Japan goes for secondhand iPhones",
        // posteyeicon : <AiOutlineEye/>,
        // postmsgicon : <TbMessage2/>,
        // postdateicon : <RxDot/>,
        postimageblog : '/images/blog-img1.jpg',
        postuser : '/images/user-2.jpg',
        postviewdata : '5235',
        posttotalmsg : '3',
        postdate : 'Wed, Jul 19',
        postreadtime : '2 min Read',
        posttype : 'Gadget',
    },
    {
        posttitle: "As yen tumbles, gadget-loving Japan goes for secondhand iPhones",
        postsub: "As yen tumbles, gadget-loving Japan goes for secondhand iPhones As yen tumbles, gadget-loving Japan goes for secondhand iPhonesAs yen tumbles, gadget-loving Japan goes for secondhand iPhonesAs yen tumbles, gadget-loving Japan goes for secondhand iPhones",
        // posteyeicon : <AiOutlineEye/>,
        // postmsgicon : <TbMessage2/>,
        // postdateicon : <RxDot/>,
        postimageblog : '/images/blog-img1.jpg',
        postuser : '/images/user-2.jpg',
        postviewdata : '5235',
        posttotalmsg : '3',
        postdate : 'Wed, Jul 19',
        postreadtime : '2 min Read',
        posttype : 'Gadget',
    },
    {
        posttitle: "As yen tumbles, gadget-loving Japan goes for secondhand iPhones",
        postsub: "As yen tumbles, gadget-loving Japan goes for secondhand iPhones As yen tumbles, gadget-loving Japan goes for secondhand iPhonesAs yen tumbles, gadget-loving Japan goes for secondhand iPhonesAs yen tumbles, gadget-loving Japan goes for secondhand iPhones",
        // posteyeicon : <AiOutlineEye/>,
        // postmsgicon : <TbMessage2/>,
        // postdateicon : <RxDot/>,
        postimageblog : '/images/blog-img1.jpg',
        postuser : '/images/user-2.jpg',
        postviewdata : '5235',
        posttotalmsg : '3',
        postdate : 'Wed, Jul 19',
        postreadtime : '2 min Read',
        posttype : 'Gadget',
    },
]